[workspace]
authors = ["mthakorecern <mitanshu.thakore@cern.ch>"]
channels = ["conda-forge"]
name = "cuda_workspace"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13, <3.14"

[system-requirements]
cuda = "12"

[feature.cpu.dependencies]
pytorch-cpu = ">=2.7.0,<3"

[feature.gpu.system-requirements]
cuda = "12"

[feature.gpu.target.linux-64.dependencies]
cuda-version = "12.9.*"
pytorch-gpu = ">=2.7.0,<3"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
